import './globals.css';
import { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import { RoutesExample } from '@/components/routes-example';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html>
      <body>
        <RoutesExample />

        {children}
      </body>
    </html>
  );
}
